### ISSUE TITLE
Players create a playlist together via the web

### ISSUE THREAD

**Issue by rakuri255** [DoubleDee73/ultrastarCatalog#3]
A collaborative playlist would be a nice feature.

Users should be able to select their favorite songs, which are then written into a playlist.
Maybe with an optional voting with +1 or -1 of all users if it really should be added to the playlist.

The story:
Planning a karaoke party for the Weekend and the singer should vote for the songs to sing before the party starts.

**Comment by DoubleDee73** [comment]
This works already without the voting
